"""
ReScene AI — Style transfer wrapper (AdaIN / Reinhard LAB colour transfer).

Real implementation uses SPADE (Spatially-Adaptive Denormalization) or
GauGAN2 conditioned on a semantic segmentation map + style vector.

This implementation uses Reinhard's LAB colour-statistics transfer — a
principled, parameter-free method that:
  1. Converts source and reference to CIE LAB colour space.
  2. For each channel, shifts the source's mean and scales its std to match
     the reference image's statistics (AdaIN at the pixel level).
  3. Blends the result with the original to preserve scene structure.
  4. Applies style-specific post-processing (brightness, contrast, grain,
     sharpness) to reinforce the perceptual character of each style.

Reference images are generated by generate_styles.py and live in data/styles/.
When a reference image is missing, the legacy hue-rotation fallback is used.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import cv2
import numpy as np
import torch

from config import Config, STYLES

logger = logging.getLogger(__name__)

# Chroma (A, B channels) transfer strength — how far to shift colour palette
_CHROMA_STRENGTH: float = 0.55

# Luminance (L channel) transfer strength — kept very low to preserve room lighting.
# This is the key quality improvement: shifting luminance makes rooms look muddy;
# shifting only chroma gives "same room, different palette."
_L_STRENGTH: dict[str, float] = {
    "Scandinavian":       0.08,   # barely touch brightness — keep the room airy
    "Industrial":         0.22,   # allow slight darkening toward charcoal
    "Bohemian":           0.14,   # subtle warm-dark push
    "Mid-Century Modern": 0.12,
    "Minimalist":         0.05,   # almost pure luminance preservation
    "Coastal":            0.10,
}

# Per-style post-processing: brightness offset, contrast scale, grain std, sharpness
_STYLE_POST: dict[str, dict[str, float]] = {
    "Scandinavian":       {"brightness":  0.05, "contrast": -0.02, "grain": 0.006, "sharp":  0.2},
    "Industrial":         {"brightness": -0.04, "contrast":  0.08, "grain": 0.012, "sharp":  0.4},
    "Bohemian":           {"brightness":  0.02, "contrast":  0.04, "grain": 0.010, "sharp":  0.0},
    "Mid-Century Modern": {"brightness":  0.01, "contrast":  0.05, "grain": 0.008, "sharp":  0.2},
    "Minimalist":         {"brightness":  0.04, "contrast": -0.06, "grain": 0.003, "sharp": -0.1},
    "Coastal":            {"brightness":  0.04, "contrast": -0.01, "grain": 0.005, "sharp":  0.1},
}

# Legacy fallback parameters (used when no reference image exists)
_HUE_SHIFT: dict[str, int] = {
    "Scandinavian": 0, "Industrial": 10, "Bohemian": 20,
    "Mid-Century Modern": -15, "Minimalist": 0, "Coastal": 15,
}
_SAT_SCALE: dict[str, float] = {
    "Scandinavian": 0.6, "Industrial": 0.4, "Bohemian": 1.4,
    "Mid-Century Modern": 1.1, "Minimalist": 0.5, "Coastal": 0.9,
}


class StyleTransferWrapper:
    """AdaIN / Reinhard LAB colour-transfer style wrapper."""

    def __init__(self, config: Config) -> None:
        self._config = config
        self._model: Any = None
        self._ref_cache: dict[str, np.ndarray] = {}

    def load(self) -> None:
        logger.info("Loading style transfer (Reinhard LAB + post-processing, no weights).")
        self._model = True
        self._ref_cache = {}
        logger.info("Style transfer ready.")

    def unload(self) -> None:
        self._model = None
        self._ref_cache = {}
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        logger.info("Style transfer unloaded.")

    def is_loaded(self) -> bool:
        return self._model is not None

    def predict(
        self,
        image: np.ndarray,
        style_name: str | None = None,
        style_image: np.ndarray | None = None,
        segmentation_map: np.ndarray | None = None,
    ) -> np.ndarray:
        """Apply style transfer to *image*.

        Parameters
        ----------
        image            : H×W×3 uint8 RGB
        style_name       : one of the keys in config.STYLES
        style_image      : explicit reference image (overrides style_name lookup)
        segmentation_map : ignored (reserved for future SPADE integration)

        Returns
        -------
        styled : H×W×3 uint8 RGB
        """
        if not self.is_loaded():
            raise RuntimeError("StyleTransfer not loaded. Call load() first.")

        name = style_name or "Minimalist"

        ref = style_image if style_image is not None else self._load_reference(name)

        if ref is not None:
            l_str = _L_STRENGTH.get(name, 0.12)
            styled = _lab_color_transfer(image, ref, _CHROMA_STRENGTH, l_str)
        else:
            logger.warning("No reference image for '%s'; using hue-shift fallback.", name)
            styled = _hue_shift_fallback(image, name)

        return _post_process(styled, _STYLE_POST.get(name, {}))

    # ------------------------------------------------------------------

    def _load_reference(self, name: str) -> np.ndarray | None:
        if name in self._ref_cache:
            return self._ref_cache[name]
        path = STYLES.get(name)
        if path is None or not Path(path).exists():
            return None
        bgr = cv2.imread(str(path))
        if bgr is None:
            return None
        rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
        self._ref_cache[name] = rgb
        logger.debug("Loaded style reference '%s' from %s", name, path)
        return rgb


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

def _lab_color_transfer(
    source: np.ndarray,
    reference: np.ndarray,
    chroma_strength: float,
    l_strength: float = 0.10,
) -> np.ndarray:
    """Reinhard per-channel mean+std transfer in CIE LAB colour space.

    Luminance (L) is shifted only slightly so the room's natural lighting is
    preserved.  Chroma (A, B) is shifted more strongly to apply the style palette.
    This avoids the "muddy / colour-cast" artefact of full equal-strength transfer.
    """
    src_lab = cv2.cvtColor(source, cv2.COLOR_RGB2LAB).astype(np.float32)

    ref_rs = cv2.resize(reference, (source.shape[1], source.shape[0]),
                        interpolation=cv2.INTER_AREA)
    ref_lab = cv2.cvtColor(ref_rs, cv2.COLOR_RGB2LAB).astype(np.float32)

    # Per-channel strengths: L=luminance barely touched, A/B=chroma fully shifted
    strengths = [l_strength, chroma_strength, chroma_strength]

    result = src_lab.copy()
    for c, s in enumerate(strengths):
        src_mu, src_sd = src_lab[:, :, c].mean(), src_lab[:, :, c].std() + 1e-6
        ref_mu, ref_sd = ref_lab[:, :, c].mean(), ref_lab[:, :, c].std() + 1e-6
        transferred = (src_lab[:, :, c] - src_mu) * (ref_sd / src_sd) + ref_mu
        result[:, :, c] = src_lab[:, :, c] * (1.0 - s) + transferred * s

    return cv2.cvtColor(np.clip(result, 0, 255).astype(np.uint8), cv2.COLOR_LAB2RGB)


def _hue_shift_fallback(image: np.ndarray, name: str) -> np.ndarray:
    """Legacy hue-rotation + saturation scale when no reference image exists."""
    hsv = cv2.cvtColor(image, cv2.COLOR_RGB2HSV).astype(np.float32)
    hsv[:, :, 0] = (hsv[:, :, 0] + _HUE_SHIFT.get(name, 0)) % 180
    hsv[:, :, 1] = np.clip(hsv[:, :, 1] * _SAT_SCALE.get(name, 1.0), 0, 255)
    return cv2.cvtColor(hsv.astype(np.uint8), cv2.COLOR_HSV2RGB)


def _post_process(image: np.ndarray, params: dict) -> np.ndarray:
    """Brightness / contrast / grain / sharpness adjustments."""
    if not params:
        return image

    f = image.astype(np.float32) / 255.0
    brightness = params.get("brightness", 0.0)
    contrast   = params.get("contrast",   0.0)
    grain      = params.get("grain",      0.0)
    sharp      = params.get("sharp",      0.0)

    f = f * (1.0 + contrast) + brightness
    if grain > 0.0:
        f += np.random.normal(0.0, grain, f.shape).astype(np.float32)
    f = np.clip(f, 0.0, 1.0)
    out = (f * 255).astype(np.uint8)

    if sharp > 0.1:
        blurred = cv2.GaussianBlur(out, (0, 0), 3)
        out = cv2.addWeighted(out, 1.0 + sharp, blurred, -sharp, 0)
    elif sharp < -0.05:
        sigma = abs(sharp) * 6.0
        k = max(3, int(sigma * 2) | 1)
        out = cv2.GaussianBlur(out, (k, k), sigma)

    return out
